# Generated by Django 4.2.1 on 2023-06-20 05:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_topic_room_host_message_room_topic"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"ordering": ["-updated", "-created"]},
        ),
    ]
