# Generated by Django 4.2.1 on 2023-06-20 08:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_alter_room_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="message",
            old_name="value",
            new_name="body",
        ),
    ]
